# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-26 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='presente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, unique=True)),
                ('descricao', models.TextField()),
                ('comprado', models.BooleanField()),
                ('img', models.ImageField(upload_to='fotopresente')),
                ('link', models.CharField(max_length=350)),
            ],
        ),
    ]
