# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, unique=True)),
                ('presenca', models.BooleanField()),
                ('npessoas', models.IntegerField()),
            ],
        ),
    ]
